project:
  type: website
  output-dir: _site

website:
  title: "Dave Wright"
  search:
    show-item-context: true
  navbar:
    search: true
    
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - posts.qmd
      - talks.qmd
      - projects.qmd
    repo-actions:
      - source
      - issue
  open-graph: true

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    page-layout: full
    code-link: true

execute:
  freeze: auto
  cache: true
